version: '3.1'

services:
   db:
     image: mysql
     environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: testDb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: password12
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   DockerTestApp:
     depends_on:
       - db
     image: docker-test-mysql
     build:
       context: .
     ports:
       - "8090:5000"
     restart: always
     
volumes:
  dbdata: